{{- range .Values.teams }}
{{- $teamName := .name }}
{{- range .namespaces }}
{{- if and (hasKey . "networkPolicy") (and (hasKey .networkPolicy "enabled") .networkPolicy.enabled) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $teamName }}-deny-by-default
  namespace: {{ .name }}
spec:
  podSelector:
    ingress: []
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $teamName }}-allow-same-namespace
  namespace: {{ .name }}
spec:
  podSelector:
    ingress:
      - from:
        - podSelector: {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $teamName }}-allow-from-openshift-ingress
namespace: {{ .name }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: ingress
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $teamName }}-allow-from-openshift-monitoring
namespace: {{ .name }}
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
{{- end }}
{{- end }}
{{- end }}


